// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOKGqy39pF6kMcj3LTRYymRKVCZFyscLw',
    appId: '1:1007118840094:web:aa790370df7525c226590f',
    messagingSenderId: '1007118840094',
    projectId: 'instagramapp-dbe8a',
    authDomain: 'instagramapp-dbe8a.firebaseapp.com',
    storageBucket: 'instagramapp-dbe8a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLK1e3I3mbNa0xvjOb_t0_ibtS1XL_ibI',
    appId: '1:1007118840094:android:53e5de3b6ed38fd026590f',
    messagingSenderId: '1007118840094',
    projectId: 'instagramapp-dbe8a',
    storageBucket: 'instagramapp-dbe8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY-omRRtQKsGuwjNxbTTKhmUTux5KGVhI',
    appId: '1:1007118840094:ios:5703ab7c7140eb8726590f',
    messagingSenderId: '1007118840094',
    projectId: 'instagramapp-dbe8a',
    storageBucket: 'instagramapp-dbe8a.firebasestorage.app',
    iosBundleId: 'com.example.instagramApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY-omRRtQKsGuwjNxbTTKhmUTux5KGVhI',
    appId: '1:1007118840094:ios:5703ab7c7140eb8726590f',
    messagingSenderId: '1007118840094',
    projectId: 'instagramapp-dbe8a',
    storageBucket: 'instagramapp-dbe8a.firebasestorage.app',
    iosBundleId: 'com.example.instagramApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOKGqy39pF6kMcj3LTRYymRKVCZFyscLw',
    appId: '1:1007118840094:web:2097ca0fc8c1fb2f26590f',
    messagingSenderId: '1007118840094',
    projectId: 'instagramapp-dbe8a',
    authDomain: 'instagramapp-dbe8a.firebaseapp.com',
    storageBucket: 'instagramapp-dbe8a.firebasestorage.app',
  );

}